# Generated by Django 4.2 on 2023-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
